// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADvq-Qm8xQ1uwj7f2NAA0vIEBIi5F2DK0',
    appId: '1:11809126159:web:a2bb6e3146edfa9f6c307a',
    messagingSenderId: '11809126159',
    projectId: 'expense-tracker-f5e2f',
    authDomain: 'expense-tracker-f5e2f.firebaseapp.com',
    storageBucket: 'expense-tracker-f5e2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1pUdgdlfR1lKTkinlCYIB0vJhg1O6Kis',
    appId: '1:11809126159:android:e20ca471bc4fad236c307a',
    messagingSenderId: '11809126159',
    projectId: 'expense-tracker-f5e2f',
    storageBucket: 'expense-tracker-f5e2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ODfwSe6nlT5QqqEHcj-UNagg6MI_3lA',
    appId: '1:11809126159:ios:7583ef685f019f786c307a',
    messagingSenderId: '11809126159',
    projectId: 'expense-tracker-f5e2f',
    storageBucket: 'expense-tracker-f5e2f.appspot.com',
    iosBundleId: 'com.example.task5ExpenseTrackerWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-ODfwSe6nlT5QqqEHcj-UNagg6MI_3lA',
    appId: '1:11809126159:ios:7583ef685f019f786c307a',
    messagingSenderId: '11809126159',
    projectId: 'expense-tracker-f5e2f',
    storageBucket: 'expense-tracker-f5e2f.appspot.com',
    iosBundleId: 'com.example.task5ExpenseTrackerWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADvq-Qm8xQ1uwj7f2NAA0vIEBIi5F2DK0',
    appId: '1:11809126159:web:b2816a12317438f86c307a',
    messagingSenderId: '11809126159',
    projectId: 'expense-tracker-f5e2f',
    authDomain: 'expense-tracker-f5e2f.firebaseapp.com',
    storageBucket: 'expense-tracker-f5e2f.appspot.com',
  );
}
